# Site settings
title: Icovn's blog
email: quanghuy.ico@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  In the spirit of "Idea worth spreading"
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
paginate:	5 # The number of posts to show per page on your homepage
paginate_path: "/blog/page:num/"
google_analytics: UA-53825430-2

# Profile
name: 'Nguyễn Quang Huy'
bio: >
  A software developer, born in Bac Ninh, graduated from Hanoi National University, live in Ha Noi.
author_image: "/assets/images/author.jpg"
twitter_username: ico_vn
github_username:  icovn

# Build settings
markdown: kramdown
kramdown:
  input: GFM
#  parse_block_html: true

#markdown: redcarpet
#redcarpet:
#  extensions: ["tables", "fenced_code_blocks"]

theme: minima

gems:
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock

# Plugin
tag_page_layout: tag_page
tag_page_dir: tag
